Algoritmo "exemplo estrutura de repetição simples"
// Disciplina  :[Lógica de Programação com javascript]
// Professor   : Jailson Obama
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : João
// Data atual  : 05/09/2024
Var
   numero: inteiro

Inicio
   escreval("Digite um numero inteiro")
   leia(numero)

   se numero < 10 entao
      escreval("Numero menor que 10")

   fimse


Fimalgoritmo